### ISSUE TITLE
Read Funlife blog

### ISSUE THREAD

**Issue by phi4grv** [threejeis/-#101]
https://funlife78.wordpress.com/2016/08/15/
https://funlife78.wordpress.com/2016/08/16/
https://funlife78.wordpress.com/2016/08/17/
https://funlife78.wordpress.com/2016/08/18/
https://funlife78.wordpress.com/2016/08/20/
https://funlife78.wordpress.com/2016/08/21/

**Comment by jjuuhhoo9999** [comment]
Together, pretty good but not a whole lot of people's interest. Alone, 1 story is short. HE need's to get people's interest. He also needs to work on his spelling and vocabulary.
