### ISSUE TITLE
Write blog on anything

### ISSUE THREAD

**Issue by phi4grv** [threejeis/-#110]

**Comment by jjuuhhoo9999** [comment]
add on
https://medium.com/@jjcraft94/eragon-the-1st-book-of-the-inheritance-cycle-18a3d3f872b9

**Comment by jjuuhhoo9999** [comment]
add on
https://medium.com/@jjcraft94/eragon-the-1st-book-of-the-inheritance-cycle-18a3d3f872b9
|: - {
