### ISSUE TITLE
write a (good) blog about wormy/nibbles

### ISSUE THREAD

**Issue by jjcraft94** [threejeis/-#212]
* Introduce wormy - very simple.
* How did I make it. - How long, what language, ...
* New thing.
  - First automatic moving object.
* What did I learn.
  - State. 
  - Make intro and out for the first time.
  - Sound effect. Background music
* How did I feel while I make it.
  - sometime it was frustrating, sometime is was easy.
  - When it's done, feel relief and happy
* Plan
  - Anything want to improve?
  - Next game is tetris.
* Say anything  to readers.
* Ending

**Comment by phi4grv** [comment]
Make first draft  by Sunday

**Comment by jjcraft94** [comment]
https://medium.com/@jjcraft94/wormy-the-clone-of-nibbles-afb5104791a2
