### ISSUE TITLE
Watch gimp tutorial "GIMP in Less Than 10 Minutes: Beginners Guide".

### ISSUE THREAD

**Issue by phi4grv** [threejeis/-#271]
https://www.youtube.com/watch?v=_L_MMU22bAw&list=PL_7viLFyJ7sAnEAuzh8ltHGw5WcDW6LLz

**Comment by phi4grv** [comment]
Watched on 31 Mar.
It is a quick and brief introduction.

**Comment by jjcraft94** [comment]
not watched yet

**Comment by jjcraft94** [comment]
watched
