### ISSUE TITLE
Watch Guide to Blender 2.8 by Blender Guru

### ISSUE THREAD

**Issue by phi4grv** [threejeis/-#273]
It has 3 parts.
Part 1: https://www.youtube.com/watch?v=lPVpg4_POww&t=13s

**Comment by phi4grv** [comment]
Watched on 31 Mars.
Too many things in short video.

**Comment by jjcraft94** [comment]
Watched all 3 videos     /\
The day is right there     |

**Comment by jjcraft94** [comment]
Watched all 3 videos on the 1st of april
