### ISSUE TITLE
Read one kids blog

### ISSUE THREAD

**Issue by phi4grv** [threejeis/-#93]

**Comment by phi4grv** [comment]
http://kidsblogclub.com/disneys-moana-wayfinding-with-code-helping-kids-learn-code/

**Comment by jjuuhhoo9999** [comment]
Moana was good and entertains kids very much while teaching them.
However, some people don't like Moana and might like it less and could have a larger group of people.
Also, doing this is like playing the game so they might get distracted but certainly get's their interest.
Overall, it's pretty good.
